# Generated by Django 4.2.2 on 2023-07-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "serial_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("asset_type", models.CharField(max_length=50)),
                ("model_type", models.CharField(max_length=50)),
                ("model_number", models.CharField(max_length=50)),
                ("mac_address", models.CharField(max_length=50)),
                ("os", models.BooleanField(default=False, max_length=50)),
                ("wake_on_lan", models.BooleanField(default=False, max_length=50)),
                ("kav", models.BooleanField(default=False, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Working", "Working"), ("Faulty", "Faulty")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "personal_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.section"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.station"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticket_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "ict_officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="assets.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeployedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_location", models.CharField(max_length=50)),
                ("current_location", models.CharField(max_length=50)),
                (
                    "movement_form",
                    models.FileField(default=None, upload_to="scanned_forms/"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("NEW DEPLOYEMENT", "NEW DEPLOYEMENT"),
                            ("REDEPLOYMENT", "REDEPLOYEMENT"),
                            ("REDEPLOYMENT", "RE-LOCATION"),
                            ("CHANGE OF OWNERSHIP", "CHANGE OF OWNERSHIP"),
                            ("SURRENDER", "SURRENDER"),
                            ("EXIT WITH", "EXIT WITH"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assets.asset",
                    ),
                ),
                (
                    "current_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_user",
                        to="assets.user",
                    ),
                ),
                (
                    "previous_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="previous_user",
                        to="assets.user",
                    ),
                ),
                (
                    "workticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.ticket"
                    ),
                ),
            ],
        ),
    ]
