# Generated by Django 4.2.2 on 2023-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="station",
            new_name="Department",
        ),
        migrations.AlterField(
            model_name="asset",
            name="mac_address",
            field=models.CharField(default="", max_length=50),
        ),
    ]
